### ISSUE TITLE
[FEAT/UI]: Improve Login and Signup UI

### ISSUE THREAD

**Issue by ayushsoni1010** [ayushsoni1010/spendify-react#6]

**Comment by saimaheshtaduri** [comment]
Can you elaborate what you need exactly. I can work on it, if you assign me @ayushsoni1010

**Comment by ayushsoni1010** [comment]
Hey @saimaheshtaduri👋
Thanks for contributing to **Spendify**

Currently, I am working on the Login and Signup UI, as of now for the authorization setup I had made a general UI. I need a few designs for both UI and then later we have to convert them into code.
