### ISSUE TITLE
[FEAT/UI]: Design a Logo for Spendify

### ISSUE THREAD

**Issue by ayushsoni1010** [ayushsoni1010/spendify-react#7]

**Comment by KaranSinghBisht** [comment]
Hey @ayushsoni1010, Can you elaborate on the type of logo you are looking for?

**Comment by ayushsoni1010** [comment]
Hey @KaranSinghBisht 
Thanks for the help in logo making, but I have already worked on it.

Hope you find some other issues to work on :)
